### ISSUE TITLE
Accessing store in Electron Main.js before preload?

### ISSUE THREAD

**Issue by heart-of-code** [reZach/secure-electron-store#1]
Hey! This is less of a bug and more of a question 😄 

In the electron-store package it seems pretty easy to access the data in Main to do things like store/retrieve the window size and coordinates so that, for example, if the user exits with the app at 500px wide, we can load it that way on the next launch.

I'm not sure how to do that with the secure-electron-store bindings. For something like this is it safe to just import the 'electron-store' package and use it directly?

**Comment by reZach** [comment]
Hi @heart-of-code, thanks for the question!

It _seems_ easy, but right now there's no way to do that as of today 😄 . 

Can you list out any possible scenario you might have to use the values in the store in main.js and we can figure out the best possible solution? (I _do_ think that we can easily expose the contents of the store within main.js to use for say the browser size, I just want to tease out other use cases you can think of before solutioning).

**Comment by heart-of-code** [comment]
I re-read the BrowserWindow documentation, I think the total list would be:

- X, Y coordinates
- width, height
- was it maximized (true/false)

I think, without finagling anything else, this could be achieved by hiding the BrowserWindow at the onset, opening the store in the renderer process, and returning the stored values via IPC, signaling to Main to apply the values and show the window...

However, in Electron-Store's documentation they mention that it can be used in the Main process as well as Renderer. Since this library is built around electron-store, we have that package already anyways, I guess we could just require() it directly?

I also found some other libraries such as [electron-window-state](https://github.com/mawie81/electron-window-state) that can do it, but I don't want to haphazardously store or retrieve data

**Comment by reZach** [comment]
Okay, thanks for listing out all the fields you might want to dynamically use.

Yes, that is an option. Let me think about how best we can approach it, your idea might be the best. I was thinking to simply return the whole store right in the main process, but what if a user needs to pass in a passkey - this option won't do.

This library is _inspired_ by electron-store, not built around it 😄 .
I can see what I can do in the coming days for you?

**Comment by heart-of-code** [comment]
> This library is inspired by electron-store, not built around it

Oops! That is an important distinction, my bad 😅

> I can see what I can do in the coming days for you?

Thanks!! If the conclusion we reach is to use the idea I posted here or something else that minimizes the work needed to be done, that's totally fine! Its not a bug or anything like that 😁

**Comment by reZach** [comment]
@heart-of-code Thanks for your patience. I've pushed [an update](https://github.com/reZach/secure-electron-store/releases/tag/v1.2.0) that has this now working, and a corresponding update to [`secure-electron-template`](https://github.com/reZach/secure-electron-template), ([v4.1.0](https://github.com/reZach/secure-electron-template/releases/tag/v4.1.0)) to support the change.

The related documentation you can find for this [is right here](https://github.com/reZach/secure-electron-store#using-the-store-from-the-main-process). Let me know if you find bugs or any questions.

**Comment by heart-of-code** [comment]
Thank you!! Sorry, I forgot to close this out
