### ISSUE TITLE
Invalid path in renderer

### ISSUE THREAD

**Issue by art-in** [reZach/secure-electron-store#12]
"--storePath=" not cut out of the `options.path`

I believe you forgot to update separator from ":" to "=" in recent changes [here](https://github.com/reZach/secure-electron-store/blob/4a480827379fd002c6a481b27230b8274ab0fd3a/src/index.js#L79)

**Comment by reZach** [comment]
Thanks for reporting this @art-in - I [pushed up a release](https://github.com/reZach/secure-electron-store/releases/tag/v4.0.2) that should fix this issue. Please re-open if you continue to have issues after upgrading the package to the latest.
