### ISSUE TITLE
cannot set passkey

### ISSUE THREAD

**Issue by art-in** [reZach/secure-electron-store#13]
```
"[secure-electron-store:main]=> received a request to update the passkey to 'undefined'"
```

receiving above debug log after calling:

```
window.electron.store.send(savePasskeyRequest, "password")
```

probably because ["key" here](https://github.com/reZach/secure-electron-store/blob/4a480827379fd002c6a481b27230b8274ab0fd3a/src/index.js#L296) should be "passkey", as this is what listener expects

**Comment by reZach** [comment]
Thanks for reporting this @art-in - I [pushed up a release](https://github.com/reZach/secure-electron-store/releases/tag/v4.0.2) that should fix this issue. Please re-open if you continue to have issues after upgrading the package to the latest.
