### ISSUE TITLE
PR to electron store?

### ISSUE THREAD

**Issue by lacymorrow** [reZach/secure-electron-store#9]
Since this is well thought-out and so many folks use @sindresorhus packages, why not PR this to the `electron-store` repo?

I believe Sindre wrote `conf` as well, so everything should be possible to update to be as secure, and it would help more projects.

**Comment by reZach** [comment]
It appears he already is communicating via IPC (https://github.com/sindresorhus/electron-store#initrenderer), that is the secure way to do it.

**Comment by reZach** [comment]
@lacymorrow The feature set is pretty comparable between these, and given his package is using IPC, it's secure to use as well. I'd like to keep and maintain this package, but you are free to use `electron-store` if you'd like. Thanks for your input here!
